### ISSUE TITLE
Java opensim-gui customisation

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensim-gui#1]
fix the visualiser window problem

**Comment by idhamari** [comment]
the visualiser is working 
the problem is that the previous installation of netbeans was somehow corrupted (system variables)
reinstalling fixed the problem
![2020-01-26_22-13-34](https://user-images.githubusercontent.com/37770658/73141989-0adad700-408a-11ea-83bf-ca9f4bb2ee20.png)

**Comment by idhamari** [comment]
This issue is now closed!

**Comment by idhamari** [comment]
@yasseerr  if you can run this in the scripting shell window there should be no problem regarding the scripting:

     2+3

**Comment by idhamari** [comment]
@yasseerr  please create a new issue for the first task in the milestone and start working on it.

**Comment by yasseerr** [comment]
script working ...
starting the first issue
![2020-01-26_22-49-07](https://user-images.githubusercontent.com/37770658/73142388-247e1d80-408e-11ea-81bc-9c0aa6714ef0.png)
