### ISSUE TITLE
Implement an open model file by drag and drop

### ISSUE THREAD

**Issue by yasseerr** [VisSimKoblenz/opensim-gui#2]
### Steps to reproduce
find the place to plug the code
using swig to implement drag and drop
starting by just models
### Expected result
fully loaded model when its file has been dragged to the scene
### Actual result
no draging functionalities
(include screen grabs where appropriate)

**Comment by yasseerr** [comment]
@idhamari  i need the path for the Main View/Frame Class if you can provide in the project

**Comment by idhamari** [comment]
Unfortunately, I don't know much about the gui structure. I think the sub project "view" is where you should start.

**Comment by idhamari** [comment]
I think the main challenges for the customization tasks are how to finding different stuff and maintaining the connection with other sub-project. 

Usually, I use "find" in netbeans and searching the github repository on the website. I think some of the windows are created programmatically and some you can find there forms.

**Comment by yasseerr** [comment]
i found that the dragNdrop is already implemented but not for all the panels like in the gif
should we apply it everywhere
the link for the class
\opensim-gui\Gui\opensim\view\src\org\opensim\view\pub\OpenSimDragNDropHandler.java
![2020-01-27_14-12-45](https://user-images.githubusercontent.com/37770658/73177333-0dcbdb00-410f-11ea-9bd2-09f7649f119e.gif)
e

**Comment by idhamari** [comment]
Thanks for the feedback. 

>should we apply it everywhere

No need. If it is work somehow, this is enough. We will do this later In the qt interface. Please proceed to the next issue. This issue is now closed.

**Comment by idhamari** [comment]
Note: I tested this in Linux and it didn't work.
