### ISSUE TITLE
Implement rename body in the body popup menu and in the properties table.

### ISSUE THREAD

**Issue by yasseerr** [VisSimKoblenz/opensim-gui#3]
### Steps to reproduce
find the menu class
add the rename option
create a rename action to the body
apply the action 
### Expected result
body renamed  and saved
### Actual result
renaming only enabled for the model

**Comment by yasseerr** [comment]
@idhamari  should we apply the renaming in the parent body object or for it children

**Comment by idhamari** [comment]
@yasseerr  when you click on a body, a popup appear, we need to have the rename in this popup menu of the body.

**Comment by yasseerr** [comment]
trying to structure the project and the other issuses will follow

**Comment by yasseerr** [comment]
trying to find a way to alter the compiled code. aparantly the code respensible for the body popup menu is precompiled :
![2020-01-28_19-25-42](https://user-images.githubusercontent.com/37770658/73293310-f1f63100-4203-11ea-85a2-34d57ad5eb07.png)
![2020-01-28_19-24-42](https://user-images.githubusercontent.com/37770658/73293336-fde1f300-4203-11ea-85aa-088746f2c58a.png)
![2020-01-28_17-01-20](https://user-images.githubusercontent.com/37770658/73293686-a2fccb80-4204-11ea-951a-eebd5871112b.png)

**Comment by yasseerr** [comment]
@idhamari  does that note apply for our project too , befor continuing to find an entry point 
![2020-01-28_23-57-31](https://user-images.githubusercontent.com/37770658/73312882-0cdb9c00-422a-11ea-89b8-46c5f758cf1a.png)

**Comment by idhamari** [comment]
They make it clear that they do not have time to help. I think if you make a post in opensim forum that you like to help (for free) to make the gui more user friendly, some experts may help. Just make sure that your questions are clear and do not waste their time.

**Comment by idhamari** [comment]
Some tips:

* When the .osim file is loaded, there should be an action to fill the navigator with the model and its elements e.g. bodies.
   - try to search for this action so we know where are these elements.
   - this help to add action to a specific element
* When a body is right-clicked in the navigator, a popup menu appears with only 3 elements "Display", "Show axes","Show Mass Center", try to search for it and modify it.
* The modification should be changing the name property of the body object if possible or by modifying the .osim file then reload it. 
* If this is done, the next task i.e. removing a body is almost the same.

**Comment by yasseerr** [comment]
creating the OneBodyRenameAction to be added to the action list in OneBodyNode return by getAction wich kind of hide the other action using the inheritance but anyway , we are in
![2020-01-29_14-04-49](https://user-images.githubusercontent.com/37770658/73359006-27e8f300-42a0-11ea-80a6-a6618b9b84c6.png)

**Comment by idhamari** [comment]
Well done! 

if it works please push your modification to this repository so I can test it.  Please add some documentation here so beginners know what to do for similar things.

**Comment by yasseerr** [comment]
i will push the modifications now , the renaming is working but it will corrupt the files because of the dependencies with the Joints 
i m curruntly trying to change the naming there too

**Comment by idhamari** [comment]
Maybe it is easier if you use text editing e.g.

1. Open the osim file as text 
2. search for the current body name and replace it with the new one
3. save the file 
4. reload the current model.

**Comment by yasseerr** [comment]
On it , and for the modification i will reclone the reposetry because of the copied file from the model to not corrupt the repo

**Comment by idhamari** [comment]
you can create a branch e.g. opesnSimGuiTesting and push your work this branch, when everything is working we can merge the branch with the master.

**Comment by idhamari** [comment]
@yasseerr I just created a new branch testingKoblenz please use it for your work.

**Comment by yasseerr** [comment]
@idhamari  i m worried aboud combining the build and the source but i cant push the code
remote: Permission to VisSimKoblenz/opensim-gui.git denied to yasseerr.

**Comment by idhamari** [comment]
notice that some files and folders e.g. build are not uploaded because of the gitignore 

I just changed the permissions, you should be able to push now

**Comment by yasseerr** [comment]
code pushed but the .gitignore didnt ignore the java files imported from the opensim core, and i dont think that i should change the gitignore

**Comment by yasseerr** [comment]
here is the link for the changes , if you want you can alter the gitignore
Gui/opensim/view/src/org/opensim/view/nodes/OneBodyNode.java

**Comment by idhamari** [comment]
Thanks, I will test it when everything works.

**Comment by idhamari** [comment]
since opensim uses xml most of the time, it is a good idea to learn and use a good cpp xml library e.g. [RapidXML](https://sourceforge.net/projects/rapidxml/).

**Comment by idhamari** [comment]
Some classes needed for openning .osim file

 - FileOpenOsimModelAction.java
 - SimTKcommon/src/Xml.cpp  Xml::readFromFile()

**Comment by yasseerr** [comment]
@idhamari 
At the moment i'm trying to change it through the OpenSim Api 
the Model have a list of Joints wich have a list of Frames
https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1Joint.html
changing it from there will be more helty
and for the QtProject , the framwork have its own xml parser wich i m familiar with
https://doc.qt.io/qt-5/qxmlsimplereader.html
but for now i think that we dont have to touch the xml file because OpenSim c++ library already implemented it , i will report if i didnt find a solution

**Comment by idhamari** [comment]
>At the moment i'm trying to change it through the OpenSim Api

this is a good idea but if things getting complicated and took longer time then please consider the xml editing. The whole java customisation thing should not take more than one week as it is not the main task. remember that it is just helpful to get you into opensim and opensom-gui.

**Comment by yasseerr** [comment]
I found that they used Xml.cpp in the OpenSim Library and changing it from there is clear, strogling to find the Xml.cpp equivalent in Java , i think i will give it tommorow 6hrs 11-17 and then if it does not work i will switch to Xml editing

**Comment by yasseerr** [comment]
Conclusion : the java wrapper dosnt provide access to Changing the xml file throught opensim wrapped functions
there is this class SWIGTYPE_SimTK_p_XML_element but it is private, so the only way to 
apply the changes to the dependencies   is to change the OpenSimObject.setName() function source code in opensim core or create a java parser using jdk libraries XML Builder and then reload the model, i m going with the second one or tell me if you want to alter the core code
however i saw that there is multiple XML model file versions 4000/2000 that we should support

**Comment by idhamari** [comment]
Thanks for the feed back, I would go for modifying the opensim-core code, I think we can re-use this in the opensim Qt project.

**Comment by yasseerr** [comment]
for the Qt project it will not be a problem since we will be working with c++ directly(we have aaccess )
its gonna take more time duo to cmake build + access to VisSimKoblenz/opensim-core
i m gonna switch to it

**Comment by idhamari** [comment]
Since most of the XML tasks are similar (I suppose you already have some knowledge about what we need for the Qt). We can go back to these tasks later if needed but I will close them for now. 

I suggest you create a new for task 7. update Jython to get some knowledge about how opensim python works.
