### ISSUE TITLE
JV 07 update Jython to the recent version

### ISSUE THREAD

**Issue by yasseerr** [VisSimKoblenz/opensim-gui#6]
### Steps to reproduce
find how jython is integrated with the code
download and update it for the latest version or change the links 
if the download is based on links
### Expected result
latest Jython installed and working

**Comment by yasseerr** [comment]
Report:
the jython is installed in 
         \Gui\opensim\scriptingShell\release\modules\ext
when compiled in netbeans they will be copied  to
          \Gui\opensim\build\cluster\modules\ext
TheClass to configure jython is JConsole wich is includes in ScriptingShellTopComponent
the currentVersion is 2.5.2
the latest release 2.7.1 
the files were added and the code was changed according to the update
however there is an encoding problem with jython that should use cp1252 encoding 
on windows and en_GB.iso88591 on linux like in the link
https://wiki.python.org/jython/ConsoleChoices
i m trying to find a way to tell jython and java to use the specifique encoding without ruining the Os or the softwar,like in window ( chcp encoding-name) but it influence other programes . the old jython does not require to indicate the encoding so there is no handler 
![2020-02-02_16-52-51](https://user-images.githubusercontent.com/37770658/73614135-ae813580-45fc-11ea-80eb-22f4cca14c40.png)
https://stackoverflow.com/questions/30443537/how-do-i-fix-unsupportedcharsetexception-in-eclipse-kepler-luna-with-jython-pyde

**Comment by yasseerr** [comment]
@idhamari 
its has been updated in this commit :
https://github.com/VisSimKoblenz/opensim-gui/commit/3cd6f675d90c932ca652f8b6ac54120b480b2fea
![2020-02-03_15-13-10](https://user-images.githubusercontent.com/37770658/73661341-310c0280-469a-11ea-8556-f1abad25edfe.png)

**Comment by idhamari** [comment]
Well done!
